using Biblia.Application.Interfaces.Repositories;
using Biblia.Domain.Entities;
using Biblia.Domain.Enums;

namespace Biblia.Infrastructure.Repositories;

public sealed class MessageRepository : SqliteRepositoryBase, IMessageRepository
{
    public MessageRepository(Biblia.Infrastructure.AppDatabase.AppDatabase database) : base(database) { }

    public async Task<Message> CreateAsync(Message item,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO Message(Title,Description,Type,CreatedAt,UpdatedAt,Introduction,Conclusion,PreferredBibleVersionId) VALUES($title,$description,$type,$created,$updated,$introduction,$conclusion,$version); SELECT last_insert_rowid();";AddMessageParameters(cmd,item);var id=Convert.ToInt64(await cmd.ExecuteScalarAsync(token));return item with{Id=id};}
    public async Task<Message?> GetAsync(long id,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Title,Description,Type,CreatedAt,UpdatedAt,Introduction,Conclusion,PreferredBibleVersionId FROM Message WHERE Id=$id;";cmd.Parameters.AddWithValue("$id",id);await using var r=await cmd.ExecuteReaderAsync(token);return await r.ReadAsync(token)?ReadMessage(r):null;}
    public async Task<IReadOnlyList<Message>> GetAllAsync(CancellationToken token=default){var result=new List<Message>();await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Title,Description,Type,CreatedAt,UpdatedAt,Introduction,Conclusion,PreferredBibleVersionId FROM Message ORDER BY UpdatedAt DESC;";await using var r=await cmd.ExecuteReaderAsync(token);while(await r.ReadAsync(token))result.Add(ReadMessage(r));return result;}
    public async Task UpdateAsync(Message item,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="UPDATE Message SET Title=$title,Description=$description,Type=$type,UpdatedAt=$updated,Introduction=$introduction,Conclusion=$conclusion,PreferredBibleVersionId=$version WHERE Id=$id;";AddMessageParameters(cmd,item);cmd.Parameters.AddWithValue("$id",item.Id);if(await cmd.ExecuteNonQueryAsync(token)!=1)throw new KeyNotFoundException("Mensagem não encontrada.");}
    public async Task<MessageTopic> AddTopicAsync(MessageTopic item,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO MessageTopic(MessageId,Title,Content,SortOrder) VALUES($message,$title,$content,$order); SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$message",item.MessageId);cmd.Parameters.AddWithValue("$title",item.Title);AddNullable(cmd.Parameters,"$content",item.Content);cmd.Parameters.AddWithValue("$order",item.SortOrder);var id=Convert.ToInt64(await cmd.ExecuteScalarAsync(token));return item with{Id=id};}
    public async Task<IReadOnlyList<MessageTopic>> GetTopicsAsync(long messageId,CancellationToken token=default){var result=new List<MessageTopic>();await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,MessageId,Title,Content,SortOrder FROM MessageTopic WHERE MessageId=$message ORDER BY SortOrder;";cmd.Parameters.AddWithValue("$message",messageId);await using var r=await cmd.ExecuteReaderAsync(token);while(await r.ReadAsync(token))result.Add(new(r.GetInt64(0),r.GetInt64(1),r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.GetInt32(4)));return result;}
    public async Task UpdateTopicAsync(MessageTopic item,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="UPDATE MessageTopic SET Title=$title,Content=$content WHERE Id=$id;";cmd.Parameters.AddWithValue("$title",item.Title);AddNullable(cmd.Parameters,"$content",item.Content);cmd.Parameters.AddWithValue("$id",item.Id);if(await cmd.ExecuteNonQueryAsync(token)!=1)throw new KeyNotFoundException("Tópico não encontrado.");}
    public async Task DeleteTopicAsync(long id,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="DELETE FROM MessageTopic WHERE Id=$id;";cmd.Parameters.AddWithValue("$id",id);await cmd.ExecuteNonQueryAsync(token);}
    public async Task ReorderTopicsAsync(long messageId,IReadOnlyList<long> ids,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var transaction=c.BeginTransaction();try{for(var i=0;i<ids.Count;i++){await using var cmd=c.CreateCommand();cmd.Transaction=transaction;cmd.CommandText="UPDATE MessageTopic SET SortOrder=$order WHERE Id=$id AND MessageId=$message;";cmd.Parameters.AddWithValue("$order",i+1000);cmd.Parameters.AddWithValue("$id",ids[i]);cmd.Parameters.AddWithValue("$message",messageId);if(await cmd.ExecuteNonQueryAsync(token)!=1)throw new KeyNotFoundException("Tópico não encontrado.");}for(var i=0;i<ids.Count;i++){await using var cmd=c.CreateCommand();cmd.Transaction=transaction;cmd.CommandText="UPDATE MessageTopic SET SortOrder=$order WHERE Id=$id;";cmd.Parameters.AddWithValue("$order",i);cmd.Parameters.AddWithValue("$id",ids[i]);await cmd.ExecuteNonQueryAsync(token);}await transaction.CommitAsync(token);}catch{await transaction.RollbackAsync(token);throw;}}
    public async Task<MessageReference> AddReferenceAsync(MessageReference item,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO MessageReference(MessageId,ReferenceId,TopicId,SortOrder,Observation,PreferredBibleVersionId) VALUES($message,$reference,$topic,$order,$observation,$version); SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$message",item.MessageId);cmd.Parameters.AddWithValue("$reference",item.ReferenceId);AddNullable(cmd.Parameters,"$topic",item.TopicId);cmd.Parameters.AddWithValue("$order",item.SortOrder);AddNullable(cmd.Parameters,"$observation",item.Observation);AddNullable(cmd.Parameters,"$version",item.PreferredBibleVersionId);var id=Convert.ToInt64(await cmd.ExecuteScalarAsync(token));return item with{Id=id};}
    public async Task<IReadOnlyList<MessageReference>> GetReferencesAsync(long messageId,CancellationToken token=default){var result=new List<MessageReference>();await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,MessageId,ReferenceId,TopicId,SortOrder,Observation,PreferredBibleVersionId FROM MessageReference WHERE MessageId=$message ORDER BY SortOrder;";cmd.Parameters.AddWithValue("$message",messageId);await using var r=await cmd.ExecuteReaderAsync(token);while(await r.ReadAsync(token))result.Add(new(r.GetInt64(0),r.GetInt64(1),r.GetInt64(2),r.IsDBNull(3)?null:r.GetInt64(3),r.GetInt32(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetInt64(6)));return result;}
    public async Task UpdateReferenceAsync(MessageReference item,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="UPDATE MessageReference SET TopicId=$topic,Observation=$observation,PreferredBibleVersionId=$version WHERE Id=$id;";AddNullable(cmd.Parameters,"$topic",item.TopicId);AddNullable(cmd.Parameters,"$observation",item.Observation);AddNullable(cmd.Parameters,"$version",item.PreferredBibleVersionId);cmd.Parameters.AddWithValue("$id",item.Id);if(await cmd.ExecuteNonQueryAsync(token)!=1)throw new KeyNotFoundException("Referência da mensagem não encontrada.");}
    public async Task DeleteReferenceAsync(long id,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="DELETE FROM MessageReference WHERE Id=$id;";cmd.Parameters.AddWithValue("$id",id);await cmd.ExecuteNonQueryAsync(token);}
    public async Task ReorderReferencesAsync(long messageId,IReadOnlyList<long> ids,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var transaction=c.BeginTransaction();try{for(var i=0;i<ids.Count;i++){await using var cmd=c.CreateCommand();cmd.Transaction=transaction;cmd.CommandText="UPDATE MessageReference SET SortOrder=$order WHERE Id=$id AND MessageId=$message;";cmd.Parameters.AddWithValue("$order",i+1000);cmd.Parameters.AddWithValue("$id",ids[i]);cmd.Parameters.AddWithValue("$message",messageId);if(await cmd.ExecuteNonQueryAsync(token)!=1)throw new KeyNotFoundException("Referência da mensagem não encontrada.");}for(var i=0;i<ids.Count;i++){await using var cmd=c.CreateCommand();cmd.Transaction=transaction;cmd.CommandText="UPDATE MessageReference SET SortOrder=$order WHERE Id=$id;";cmd.Parameters.AddWithValue("$order",i);cmd.Parameters.AddWithValue("$id",ids[i]);await cmd.ExecuteNonQueryAsync(token);}await transaction.CommitAsync(token);}catch{await transaction.RollbackAsync(token);throw;}}
    public async Task<int> GetNextReferenceOrderAsync(long messageId,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="SELECT COALESCE(MAX(SortOrder),-1)+1 FROM MessageReference WHERE MessageId=$message;";cmd.Parameters.AddWithValue("$message",messageId);return Convert.ToInt32(await cmd.ExecuteScalarAsync(token));}
    public async Task<Message> DuplicateAsync(long messageId,string? title=null,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var transaction=c.BeginTransaction();try{var source=await GetAsync(messageId,token)??throw new KeyNotFoundException("Mensagem não encontrada.");var now=DateTimeOffset.UtcNow;var clone=source with{Id=0,Title=string.IsNullOrWhiteSpace(title)?$"{source.Title} (cópia)":title.Trim(),CreatedAt=now,UpdatedAt=now};long cloneId;await using(var insert=c.CreateCommand()){insert.Transaction=transaction;insert.CommandText="INSERT INTO Message(Title,Description,Type,CreatedAt,UpdatedAt,Introduction,Conclusion,PreferredBibleVersionId) VALUES($title,$description,$type,$created,$updated,$introduction,$conclusion,$version); SELECT last_insert_rowid();";AddMessageParameters(insert,clone);cloneId=Convert.ToInt64(await insert.ExecuteScalarAsync(token));}var oldTopics=await GetTopicsAsync(messageId,token);var mapping=new Dictionary<long,long>();foreach(var topic in oldTopics){await using var insert=c.CreateCommand();insert.Transaction=transaction;insert.CommandText="INSERT INTO MessageTopic(MessageId,Title,Content,SortOrder) VALUES($message,$title,$content,$order); SELECT last_insert_rowid();";insert.Parameters.AddWithValue("$message",cloneId);insert.Parameters.AddWithValue("$title",topic.Title);AddNullable(insert.Parameters,"$content",topic.Content);insert.Parameters.AddWithValue("$order",topic.SortOrder);mapping[topic.Id]=Convert.ToInt64(await insert.ExecuteScalarAsync(token));}foreach(var reference in await GetReferencesAsync(messageId,token)){await using var insert=c.CreateCommand();insert.Transaction=transaction;insert.CommandText="INSERT INTO MessageReference(MessageId,ReferenceId,TopicId,SortOrder,Observation,PreferredBibleVersionId) VALUES($message,$reference,$topic,$order,$observation,$version);";insert.Parameters.AddWithValue("$message",cloneId);insert.Parameters.AddWithValue("$reference",reference.ReferenceId);AddNullable(insert.Parameters,"$topic",reference.TopicId is null?null:mapping[reference.TopicId.Value]);insert.Parameters.AddWithValue("$order",reference.SortOrder);AddNullable(insert.Parameters,"$observation",reference.Observation);AddNullable(insert.Parameters,"$version",reference.PreferredBibleVersionId);await insert.ExecuteNonQueryAsync(token);}await transaction.CommitAsync(token);return clone with{Id=cloneId};}catch{await transaction.RollbackAsync(token);throw;}}
    public async Task DeleteAsync(long id,CancellationToken token=default){await using var c=await Database.OpenConnectionAsync(token);await using var cmd=c.CreateCommand();cmd.CommandText="DELETE FROM Message WHERE Id=$id;";cmd.Parameters.AddWithValue("$id",id);await cmd.ExecuteNonQueryAsync(token);}
    private static Message ReadMessage(Microsoft.Data.Sqlite.SqliteDataReader reader)=>new(reader.GetInt64(0),reader.GetString(1),reader.IsDBNull(2)?null:reader.GetString(2),(MessageType)reader.GetInt32(3),ReadDate(reader,4),ReadDate(reader,5),reader.IsDBNull(6)?null:reader.GetString(6),reader.IsDBNull(7)?null:reader.GetString(7),reader.IsDBNull(8)?null:reader.GetInt64(8));
    private static void AddMessageParameters(Microsoft.Data.Sqlite.SqliteCommand command,Message item){command.Parameters.AddWithValue("$title",item.Title);AddNullable(command.Parameters,"$description",item.Description);command.Parameters.AddWithValue("$type",(int)item.Type);command.Parameters.AddWithValue("$created",item.CreatedAt.ToString("O"));command.Parameters.AddWithValue("$updated",item.UpdatedAt.ToString("O"));AddNullable(command.Parameters,"$introduction",item.Introduction);AddNullable(command.Parameters,"$conclusion",item.Conclusion);AddNullable(command.Parameters,"$version",item.PreferredBibleVersionId);}
}
